batch_size: 512
ckpt_path: ''
data_path: '/project/data/external/ILSVRC/Data/CLS-LOC' #IMAGENET_PATH
dataset_name: imagenet
device: cuda
model_name: densenet_timm
wandb_api_key: ''
wandb_project_name: ''
